package com.meewav.android.features.auth

/** Only the entry modes generated by this build may bypass the no-query asset rule. */
internal fun isPermittedGlobeEntryQuery(encodedQuery: String?, nativeRendererEnabled: Boolean): Boolean =
    encodedQuery == "mode=real" || encodedQuery == "mode=demo" ||
        (nativeRendererEnabled && encodedQuery in setOf("mode=real&renderer=native", "mode=demo&renderer=native"))
