import {supabase} from "../../../lib/supabaseClient";
import {useEffect,useState} from 'react';
import LogeViewer from './LogeViewer';
import type {LogeState,RoomPerson} from '../roomTools.types';
type Snapshot={viewerId:string;viewerName:string;questionsOpen:boolean;questions:any[];moments:any[];experiences:any[]};
export default function AndroidLogeViewer({title,hostName,fallback,onOpenChat,roomId}:{roomId?:string;title:string;hostName:string;fallback:LogeState;onOpenChat?:()=>void}) {
 const [state,setState]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const url='/native/loge-viewer?title='+encodeURIComponent(title);
 async function cloud(command?:any){const {data,error}=await supabase.rpc(command?'rooms_loge_action_v1':'rooms_loge_read_v1',command?{p_room_id:roomId,p_action:command.type,p_payload:command}:{p_room_id:roomId});if(error)throw Error(error.message);return data;}
 async function request(command?:object){if(roomId){const next=await cloud(command);setState(next);setError('');return next;}const response=await fetch(url,command?{method:'POST',headers:{'X-Meewav-Loge':btoa(unescape(encodeURIComponent(JSON.stringify(command))))}}:undefined);const next=await response.json();if(!response.ok)throw Error(next.error||'Synchronisation indisponible');setState(next);setError('');return next;}
 useEffect(()=>{let active=true;const read=async()=>{try{if(roomId){const next=await cloud();if(active){setState(next);setError('')}return;}const response=await fetch(url);const next=await response.json();if(!response.ok)throw Error(next.error||'Synchronisation indisponible');if(active){setState(next);setError('')}}catch{if(active)setError('Impossible de synchroniser la Loge. Réessayez.')}};void read();const timer=setInterval(read,1500);return()=>{active=false;clearInterval(timer)}},[url,roomId]);
 if(!state)return <p role="status">{error||'Chargement de la Loge…'}</p>;
 const viewer:RoomPerson={id:state.viewerId,name:state.viewerName,avatarUrl:'',role:'Membre VIP',microphone:'off',camera:'off'};
 const loge={...fallback,questionsOpen:state.questionsOpen,requestQueues:{dedication:true,"face-to-face":true},questions:state.questions.map(q=>({...q,author:{...viewer,id:q.personId,name:q.personId===state.viewerId?state.viewerName:'Membre de la Loge'},invited:false,sentAt:''})),moments:state.moments.map(m=>({...m,beneficiary:viewer,requested:m.status==="pending",kind:m.format==='live'?'face-to-face':'dedication',title:m.format==='live'?`Face-à-face · ${m.minutes} min`:`Dédicace ${m.format}`,format:m.format}))} as LogeState;
 const run=async(command:object)=>{setBusy(true);try{return await request(command)}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}};
 return <>{error?<p role="alert">{error}</p>:null}<LogeViewer loge={loge} accountId={viewer.id} viewer={viewer} hostName={hostName} eligible canEngage busy={busy} requestsEnabled experiences={state.experiences} onRespondExperience={(id,accept)=>run({type:'experience',id,accept})} preview={null} onOpenChat={onOpenChat} execute={async command=>{if(command.type==='loge.request.join')return run({type:'request',format:command.kind==='face-to-face'?'live':'audio'});if(command.type==='loge.request.cancel')return run({type:'cancel-request',id:command.momentId});if(command.type==='loge.question.add')return run({type:'question',text:command.question.text});if(command.type==='loge.moment.respond')return run({type:'moment',id:command.momentId,accept:command.accept});throw Error('Action indisponible');}}/></>;
}
